### ISSUE TITLE
No fog

### ISSUE THREAD

**Issue by CubbyBear00** [JimiIT92/BetterPaleGarden#2] opened 2024-12-10 17:38 UTC
**Describe the bug**
I do not see fog in the pale garden as is shown in your pictures on your curseforge page

**Expected behavior**
I expected there to be fog

**Screenshots**

**Versions (please complete the following information)**
- Minecraft: 1.21.4
- Fabric: 0.111.0
- BetterPaleGarden: 1.0.0

**Additional context**
Everything else in the mod worksfine

**Comment by JimiIT92** [comment] 2024-12-11 14:40
Could you check if you are actually in the Pale Garden? I've noticed that sometimes the biome "spreads" in other biomes. For example I've found patches of Pale Moss inside a Dark Oak Forest that was near the Biome.

That said, in the new update there are some fixes and improvements for the Fog system, so let me know if the issue is fixed with this new version:

https://modrinth.com/mod/hendrixs-better-pale-garden/version/1.1.0-Fabric

**Closed as completed** 2024-12-23 13:08 UTC
Labels: bug
